// Auto-generated. Do not edit!

// (in-package tbug.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class goalStatusResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.robot0_thereOrNot = null;
      this.robot1_thereOrNot = null;
      this.robot2_thereOrNot = null;
    }
    else {
      if (initObj.hasOwnProperty('robot0_thereOrNot')) {
        this.robot0_thereOrNot = initObj.robot0_thereOrNot
      }
      else {
        this.robot0_thereOrNot = 0;
      }
      if (initObj.hasOwnProperty('robot1_thereOrNot')) {
        this.robot1_thereOrNot = initObj.robot1_thereOrNot
      }
      else {
        this.robot1_thereOrNot = 0;
      }
      if (initObj.hasOwnProperty('robot2_thereOrNot')) {
        this.robot2_thereOrNot = initObj.robot2_thereOrNot
      }
      else {
        this.robot2_thereOrNot = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type goalStatusResult
    // Serialize message field [robot0_thereOrNot]
    bufferOffset = _serializer.uint32(obj.robot0_thereOrNot, buffer, bufferOffset);
    // Serialize message field [robot1_thereOrNot]
    bufferOffset = _serializer.uint32(obj.robot1_thereOrNot, buffer, bufferOffset);
    // Serialize message field [robot2_thereOrNot]
    bufferOffset = _serializer.uint32(obj.robot2_thereOrNot, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type goalStatusResult
    let len;
    let data = new goalStatusResult(null);
    // Deserialize message field [robot0_thereOrNot]
    data.robot0_thereOrNot = _deserializer.uint32(buffer, bufferOffset);
    // Deserialize message field [robot1_thereOrNot]
    data.robot1_thereOrNot = _deserializer.uint32(buffer, bufferOffset);
    // Deserialize message field [robot2_thereOrNot]
    data.robot2_thereOrNot = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'tbug/goalStatusResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2ce792ce8df4eddb005f1e3ae8982006';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint32 robot0_thereOrNot
    uint32 robot1_thereOrNot
    uint32 robot2_thereOrNot
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new goalStatusResult(null);
    if (msg.robot0_thereOrNot !== undefined) {
      resolved.robot0_thereOrNot = msg.robot0_thereOrNot;
    }
    else {
      resolved.robot0_thereOrNot = 0
    }

    if (msg.robot1_thereOrNot !== undefined) {
      resolved.robot1_thereOrNot = msg.robot1_thereOrNot;
    }
    else {
      resolved.robot1_thereOrNot = 0
    }

    if (msg.robot2_thereOrNot !== undefined) {
      resolved.robot2_thereOrNot = msg.robot2_thereOrNot;
    }
    else {
      resolved.robot2_thereOrNot = 0
    }

    return resolved;
    }
};

module.exports = goalStatusResult;
