(cl:defpackage tbug-msg
  (:use )
  (:export
   "<GOALSTATUSACTION>"
   "GOALSTATUSACTION"
   "<GOALSTATUSACTIONFEEDBACK>"
   "GOALSTATUSACTIONFEEDBACK"
   "<GOALSTATUSACTIONGOAL>"
   "GOALSTATUSACTIONGOAL"
   "<GOALSTATUSACTIONRESULT>"
   "GOALSTATUSACTIONRESULT"
   "<GOALSTATUSFEEDBACK>"
   "GOALSTATUSFEEDBACK"
   "<GOALSTATUSGOAL>"
   "GOALSTATUSGOAL"
   "<GOALSTATUSRESULT>"
   "GOALSTATUSRESULT"
  ))

