; Auto-generated. Do not edit!


(cl:in-package tbug-msg)


;//! \htmlinclude goalStatusActionGoal.msg.html

(cl:defclass <goalStatusActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type tbug-msg:goalStatusGoal
    :initform (cl:make-instance 'tbug-msg:goalStatusGoal)))
)

(cl:defclass goalStatusActionGoal (<goalStatusActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <goalStatusActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'goalStatusActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tbug-msg:<goalStatusActionGoal> is deprecated: use tbug-msg:goalStatusActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <goalStatusActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tbug-msg:header-val is deprecated.  Use tbug-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <goalStatusActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tbug-msg:goal_id-val is deprecated.  Use tbug-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <goalStatusActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tbug-msg:goal-val is deprecated.  Use tbug-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <goalStatusActionGoal>) ostream)
  "Serializes a message object of type '<goalStatusActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <goalStatusActionGoal>) istream)
  "Deserializes a message object of type '<goalStatusActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<goalStatusActionGoal>)))
  "Returns string type for a message object of type '<goalStatusActionGoal>"
  "tbug/goalStatusActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'goalStatusActionGoal)))
  "Returns string type for a message object of type 'goalStatusActionGoal"
  "tbug/goalStatusActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<goalStatusActionGoal>)))
  "Returns md5sum for a message object of type '<goalStatusActionGoal>"
  "21ec54f02e557c73d2c2c4c59990d3f2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'goalStatusActionGoal)))
  "Returns md5sum for a message object of type 'goalStatusActionGoal"
  "21ec54f02e557c73d2c2c4c59990d3f2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<goalStatusActionGoal>)))
  "Returns full string definition for message of type '<goalStatusActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%goalStatusGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: tbug/goalStatusGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float64 x~%float64 y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'goalStatusActionGoal)))
  "Returns full string definition for message of type 'goalStatusActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%goalStatusGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: tbug/goalStatusGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%float64 x~%float64 y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <goalStatusActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <goalStatusActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'goalStatusActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
